import json

from confluent_kafka import Producer

BROKER = 'localhost:9092'
OUTPUT_TOPIC = "local_detector"

config = {"bootstrap.servers": BROKER}
producer = Producer(**config)

# For consuming the data generated by generate_ev44.py
CONFIG_JSON = {
    "cmd": "config",
    "input_schema": "ev44",
    "output_schema": "hs01",
    "histograms": [
        {
            "type": "dethist",
            "data_brokers": [BROKER],
            "data_topics": [OUTPUT_TOPIC],
            "tof_range": [0, 100000000],
            "det_range": [0, img.shape[0] * img.shape[1]],
            "width": 600,
            "height": 512,
            "topic": "local_visualisation",
            "id": "some_id",
            "source": "grace",
        }
    ]
}

producer.produce("local_jbi_commands", bytes(json.dumps(CONFIG_JSON), "utf-8"))
producer.flush()
